#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  sync-homebrew-tap.sh \
    --metadata-dir <path/to/dist/tap> \
    --tap-dir <path/to/homebrew-tap> \
    --homepage <project-homepage>

Notes:
  - Reads metadata files generated by release workflow (`*.env`).
  - Uses scripts/update-tap-formula.sh to write Formula/<tool>.rb.
EOF
}

require_arg() {
  local name="$1"
  local value="$2"
  if [[ -z "${value}" ]]; then
    echo "missing required argument: ${name}" >&2
    usage >&2
    exit 1
  fi
}

default_desc_for_tool() {
  local tool="$1"
  case "${tool}" in
    envlock) echo "Build environment sessions from JSON profile" ;;
    *) echo "${tool} CLI tool" ;;
  esac
}

metadata_dir=""
tap_dir=""
homepage=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --metadata-dir) metadata_dir="${2:-}"; shift 2 ;;
    --tap-dir) tap_dir="${2:-}"; shift 2 ;;
    --homepage) homepage="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_arg "--metadata-dir" "${metadata_dir}"
require_arg "--tap-dir" "${tap_dir}"
require_arg "--homepage" "${homepage}"

if [[ ! -d "${metadata_dir}" ]]; then
  echo "metadata dir not found: ${metadata_dir}" >&2
  exit 1
fi
if [[ ! -d "${tap_dir}" ]]; then
  echo "tap dir not found: ${tap_dir}" >&2
  exit 1
fi

shopt -s nullglob
files=("${metadata_dir}"/*.env)
if [[ ${#files[@]} -eq 0 ]]; then
  echo "no metadata files found in ${metadata_dir}" >&2
  exit 1
fi

for file in "${files[@]}"; do
  unset TOOL VERSION MACOS_ARM_URL MACOS_ARM_SHA256 MACOS_AMD_URL MACOS_AMD_SHA256 LINUX_AMD_URL LINUX_AMD_SHA256
  # Metadata files are generated by our own release workflow.
  # shellcheck disable=SC1090
  source "${file}"

  require_arg "TOOL" "${TOOL:-}"
  require_arg "VERSION" "${VERSION:-}"
  require_arg "MACOS_ARM_URL" "${MACOS_ARM_URL:-}"
  require_arg "MACOS_ARM_SHA256" "${MACOS_ARM_SHA256:-}"
  require_arg "MACOS_AMD_URL" "${MACOS_AMD_URL:-}"
  require_arg "MACOS_AMD_SHA256" "${MACOS_AMD_SHA256:-}"
  require_arg "LINUX_AMD_URL" "${LINUX_AMD_URL:-}"
  require_arg "LINUX_AMD_SHA256" "${LINUX_AMD_SHA256:-}"

  formula_path="${tap_dir}/Formula/${TOOL}.rb"
  scripts/update-tap-formula.sh \
    --formula "${formula_path}" \
    --tool "${TOOL}" \
    --desc "$(default_desc_for_tool "${TOOL}")" \
    --homepage "${homepage}" \
    --version "${VERSION}" \
    --macos-arm-url "${MACOS_ARM_URL}" \
    --macos-arm-sha256 "${MACOS_ARM_SHA256}" \
    --macos-amd-url "${MACOS_AMD_URL}" \
    --macos-amd-sha256 "${MACOS_AMD_SHA256}" \
    --linux-amd-url "${LINUX_AMD_URL}" \
    --linux-amd-sha256 "${LINUX_AMD_SHA256}"
done

echo "tap formulas synchronized from metadata: ${metadata_dir}"
